FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["/API", "./API"]
COPY ["/SmartHouse.Domain.Core", "./SmartHouse.Domain.Core"]
COPY ["/SmartHouse.Domain.Interfaces", "./SmartHouse.Domain.Interfaces"]
COPY ["/SmartHouse.Infrastructure.Business", "./SmartHouse.Infrastructure.Business"]
COPY ["/SmartHouse.Infrastructure.Data", "./SmartHouse.Infrastructure.Data"]
COPY ["/SmartHouse.Services.Interfaces", "./SmartHouse.Services.Interfaces"]
COPY ["/Weather", "./Weather"]
COPY ["/Tests", "./Tests"]

RUN dotnet restore Tests/TestBusiness/BusinessTest.csproj; \
	dotnet restore Tests/TestRepository/RepositoryTest.csproj; \
	dotnet restore Tests/TestApi/ApiTest.csproj; \
	dotnet restore Tests/TestApiIntegration/ApiIntegrationTest.csproj; \
	dotnet restore Tests/TestServices/ServicesTest.csproj
COPY . .
WORKDIR "Tests"

FROM build AS publish
RUN dotnet publish "TestBusiness/BusinessTest.csproj" -c Release -o /app/publish/TestBusiness; \
	dotnet publish "TestRepository/RepositoryTest.csproj" -c Release -o /app/publish/TestRepository; \
	dotnet publish "TestApi/ApiTest.csproj" -c Release -o /app/publish/TestApi; \
	dotnet publish "TestApiIntegration/ApiIntegrationTest.csproj" -c Release -o /app/publish/TestApiIntegration; \
	dotnet publish "TestServices/ServicesTest.csproj" -c Release -o /app/publish/TestServices

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

