#docker-compose.test.yml (Extended config for DEVELOPMENT env.)

version: '3.6'
services:
  tests:
    build:
      context: .
      dockerfile: DockerfileTests
    environment:
      - api_url=http://api:${INTERNAL_API_PORT}
    networks:
      - app-smart-house-network
    depends_on: 
      - api